### ISSUE TITLE
Error in Firefox and chromium

### ISSUE THREAD

**Issue by lenniezelk** [alxgibsn/rive-examples-react#4]
When i run the app I get these errors in FF(83.0 (64-bit)):
Uncaught (in promise) TypeError: Se[e] is undefined

Chromium(89.0.4328.0 (Developer Build)):
Uncaught (in promise) TypeError: Cannot read property 'value' of undefined

**Comment by alxgibsn** [comment]
Hey @lenniezelk, I believe it was caused by an update to the rive-canvas runtime. If you pull down the latest change it should work now.

**Comment by lenniezelk** [comment]
Works thanks @alxgibsn
