### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by PatrickEnnemoser** [alxgibsn/rive-examples-react#5]
Hey,

I have downloaded the project, installed the modules and startet the application. Instantly I received this error at rive.js:1.
I'm new to React and Rive, so I would be thankful for you help.

**Comment by alxgibsn** [comment]
Hi @PatrickEnnemoser, are you using the included rive files? Or swapping them out for your own? 

We recently launched a simpler version of the runtime, which should be much easier to get started with. If that would be helpful for you I can get a new example added shortly!

**Comment by estidea** [comment]
Hey @PatrickEnnemoser! I've faced the same issue as @alxgibsn 
Didn't swap files on my own.

**Comment by PatrickEnnemoser** [comment]
Hi @alxgibsn,
I didn't swapped files and clicked on Morty. There is no Animation playing and the console shows this error:
Uncaught (in promise) RuntimeError: abort(LinkError: WebAssembly.instantiate(): table import 40 is smaller than initial 765, got 708). Build with -s ASSERTIONS=1 for more info.

**Comment by alxgibsn** [comment]
Hi @PatrickEnnemoser, @estidea -- I've just updated the repository to make use of the new, simpler rive-js runtime as well as hooks and TypeScript. Be sure to run `npm install` again, and let me know if you continue to experience problems.

**Comment by PatrickEnnemoser** [comment]
Hi @alxgibsn,
thanks a lot, now it works!
